use egui::Key;

pub fn map_key(key: Key) -> Option<u32> {
    match key {
        Key::Space => Some(0x20),
        Key::Enter => Some(0xFF0D),
        Key::Tab => Some(0xFF09),
        Key::Escape => Some(0xFF1B),
        Key::Backspace => Some(0xFF08),
        Key::Insert => Some(0xFF63),
        Key::Delete => Some(0xFFFF),
        Key::Home => Some(0xFF50),
        Key::End => Some(0xFF57),
        Key::PageUp => Some(0xFF55),
        Key::PageDown => Some(0xFF56),
        Key::ArrowLeft => Some(0xFF51),
        Key::ArrowUp => Some(0xFF52),
        Key::ArrowRight => Some(0xFF53),
        Key::ArrowDown => Some(0xFF54),

        Key::F1 => Some(0xFFBE),
        Key::F2 => Some(0xFFBF),
        Key::F3 => Some(0xFFC0),
        Key::F4 => Some(0xFFC1),
        Key::F5 => Some(0xFFC2),
        Key::F6 => Some(0xFFC3),
        Key::F7 => Some(0xFFC4),
        Key::F8 => Some(0xFFC5),
        Key::F9 => Some(0xFFC6),
        Key::F10 => Some(0xFFC7),
        Key::F11 => Some(0xFFC8),
        Key::F12 => Some(0xFFC9),

        Key::A => Some(0x61),
        Key::B => Some(0x62),
        Key::C => Some(0x63),
        Key::D => Some(0x64),
        Key::E => Some(0x65),
        Key::F => Some(0x66),
        Key::G => Some(0x67),
        Key::H => Some(0x68),
        Key::I => Some(0x69),
        Key::J => Some(0x6A),
        Key::K => Some(0x6B),
        Key::L => Some(0x6C),
        Key::M => Some(0x6D),
        Key::N => Some(0x6E),
        Key::O => Some(0x6F),
        Key::P => Some(0x70),
        Key::Q => Some(0x71),
        Key::R => Some(0x72),
        Key::S => Some(0x73),
        Key::T => Some(0x74),
        Key::U => Some(0x75),
        Key::V => Some(0x76),
        Key::W => Some(0x77),
        Key::X => Some(0x78),
        Key::Y => Some(0x79),
        Key::Z => Some(0x7A),

        Key::Num0 => Some(0x30),
        Key::Num1 => Some(0x31),
        Key::Num2 => Some(0x32),
        Key::Num3 => Some(0x33),
        Key::Num4 => Some(0x34),
        Key::Num5 => Some(0x35),
        Key::Num6 => Some(0x36),
        Key::Num7 => Some(0x37),
        Key::Num8 => Some(0x38),
        Key::Num9 => Some(0x39),

        _ => None,
    }
}
