use egui::Key;

pub fn map_key(key: Key) -> Option<u32> {
    use x11::keysym::*;

    match key {
        Key::Space => Some(XK_space as u32),
        Key::Enter => Some(XK_Return as u32),
        Key::Tab => Some(XK_Tab as u32),
        Key::Escape => Some(XK_Escape as u32),
        Key::Backspace => Some(XK_BackSpace as u32),
        Key::Insert => Some(XK_Insert as u32),
        Key::Delete => Some(XK_Delete as u32),
        Key::Home => Some(XK_Home as u32),
        Key::End => Some(XK_End as u32),
        Key::PageUp => Some(XK_Page_Up as u32),
        Key::PageDown => Some(XK_Page_Down as u32),
        Key::ArrowLeft => Some(XK_Left as u32),
        Key::ArrowUp => Some(XK_Up as u32),
        Key::ArrowRight => Some(XK_Right as u32),
        Key::ArrowDown => Some(XK_Down as u32),

        Key::F1 => Some(XK_F1 as u32),
        Key::F2 => Some(XK_F2 as u32),
        Key::F3 => Some(XK_F3 as u32),
        Key::F4 => Some(XK_F4 as u32),
        Key::F5 => Some(XK_F5 as u32),
        Key::F6 => Some(XK_F6 as u32),
        Key::F7 => Some(XK_F7 as u32),
        Key::F8 => Some(XK_F8 as u32),
        Key::F9 => Some(XK_F9 as u32),
        Key::F10 => Some(XK_F10 as u32),
        Key::F11 => Some(XK_F11 as u32),
        Key::F12 => Some(XK_F12 as u32),

        Key::A => Some(XK_a as u32),
        Key::B => Some(XK_b as u32),
        Key::C => Some(XK_c as u32),
        Key::D => Some(XK_d as u32),
        Key::E => Some(XK_e as u32),
        Key::F => Some(XK_f as u32),
        Key::G => Some(XK_g as u32),
        Key::H => Some(XK_h as u32),
        Key::I => Some(XK_i as u32),
        Key::J => Some(XK_j as u32),
        Key::K => Some(XK_k as u32),
        Key::L => Some(XK_l as u32),
        Key::M => Some(XK_m as u32),
        Key::N => Some(XK_n as u32),
        Key::O => Some(XK_o as u32),
        Key::P => Some(XK_p as u32),
        Key::Q => Some(XK_q as u32),
        Key::R => Some(XK_r as u32),
        Key::S => Some(XK_s as u32),
        Key::T => Some(XK_t as u32),
        Key::U => Some(XK_u as u32),
        Key::V => Some(XK_v as u32),
        Key::W => Some(XK_w as u32),
        Key::X => Some(XK_x as u32),
        Key::Y => Some(XK_y as u32),
        Key::Z => Some(XK_z as u32),

        Key::Num0 => Some(XK_0 as u32),
        Key::Num1 => Some(XK_1 as u32),
        Key::Num2 => Some(XK_2 as u32),
        Key::Num3 => Some(XK_3 as u32),
        Key::Num4 => Some(XK_4 as u32),
        Key::Num5 => Some(XK_5 as u32),
        Key::Num6 => Some(XK_6 as u32),
        Key::Num7 => Some(XK_7 as u32),
        Key::Num8 => Some(XK_8 as u32),
        Key::Num9 => Some(XK_9 as u32),

        _ => None,
    }
}
